// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';

// user
export const USER_REQUEST = 'USER_REQUEST';
export const USER_RESPONSE = 'USER_RESPONSE';
export const USER_LOADING_ENDED = 'USER_LOADING_ENDED';

